package vaquita
import chisel3._
import chisel3.tester._
import org.scalatest.freespec.AnyFreeSpec
import chisel3.experimental.BundleLiterals._
import vaquita.configparameter.VaquitaConfig

class VecTopTest extends AnyFreeSpec with ChiselScalatestTester {
  "vec top test" in {
    implicit val config = new VaquitaConfig (32,32,32,1,true)
    test(new VaquitaTop) { dut =>
      dut.io.instr.poke("x0102f2d7".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(4.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)
      
      dut.io.instr.poke("x0200b057".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x02213157".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x0241b257".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x02623357".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x4a011457".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x4a219557".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x4a419657".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x4a619757".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x5e040857".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("xb2c51857".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x5e040957".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("xb2c55957".U)
      dut.io.rs1_data.poke(0x40400000.S)
      dut.io.hazard_rs1_data_in.poke(0x40400000.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x5e040a57".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("xb6c51a57".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x5e040b57".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("xb6c55b57".U)
      dut.io.rs1_data.poke(0x40400000.S)
      dut.io.hazard_rs1_data_in.poke(0x40400000.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x5e040c57".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("xbac51c57".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x5e040d57".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("xbac55d57".U)
      dut.io.rs1_data.poke(0x40400000.S)
      dut.io.hazard_rs1_data_in.poke(0x40400000.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)   

      dut.io.instr.poke("x5e040e57".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("xbec51e57".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x5e040f57".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("xbec55f57".U)
      dut.io.rs1_data.poke(0x40400000.S)
      dut.io.hazard_rs1_data_in.poke(0x40400000.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x5e0400d7".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("xa2c510d7".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x5e0401d7".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("xa2c551d7".U)
      dut.io.rs1_data.poke(0x40400000.S)
      dut.io.hazard_rs1_data_in.poke(0x40400000.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x5e0402d7".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("xa6c512d7".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x5e0403d7".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("xa6c553d7".U)
      dut.io.rs1_data.poke(0x40400000.S)
      dut.io.hazard_rs1_data_in.poke(0x40400000.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x5e0404d7".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("xaac514d7".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x5e0405d7".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("xaac555d7".U)
      dut.io.rs1_data.poke(0x40400000.S)
      dut.io.hazard_rs1_data_in.poke(0x40400000.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x5e0406d7".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("xaec516d7".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("x5e0407d7".U)
      dut.io.rs1_data.poke(0.S)
      dut.io.hazard_rs1_data_in.poke(0.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)

      dut.io.instr.poke("xaec557d7".U)
      dut.io.rs1_data.poke(0x40400000.S)
      dut.io.hazard_rs1_data_in.poke(0x40400000.U)
      // dut.io.vl_rs1_out.expect(0.U)    
      dut.io.dmemReq.ready.poke(true.B)
      dut.io.dmemRsp.valid.poke(true.B)
      dut.clock.step(1)






      // my normal test cases 
      // dut.io.instr.poke("x0112f2d7".U)
      // dut.io.rs1_data.poke(0.S)
      // dut.io.hazard_rs1_data_in.poke(4.U)
      // // dut.io.vl_rs1_out.expect(0.U)    
      // dut.io.dmemReq.ready.poke(true.B)
      // dut.io.dmemRsp.valid.poke(true.B)
      // dut.clock.step(1)
      // println(s"Cycle 1 completed, instr: ${dut.io.instr.peek()}")

      // dut.io.instr.poke("x0200b057".U)
      // dut.io.rs1_data.poke(0.S)
      // dut.io.hazard_rs1_data_in.poke(0.U)
      // // dut.io.vl_rs1_out.expect(0.U)    
      // dut.io.dmemReq.ready.poke(true.B)
      // dut.io.dmemRsp.valid.poke(true.B)
      // dut.clock.step(1)
      // println(s"Cycle 2 completed, instr: ${dut.io.instr.peek()}")

      // dut.io.instr.poke("x022db257".U)
      // dut.io.rs1_data.poke(0.S)
      // dut.io.hazard_rs1_data_in.poke(0.U)
      // // dut.io.vl_rs1_out.expect(0.U)    
      // dut.io.dmemReq.ready.poke(true.B)
      // dut.io.dmemRsp.valid.poke(true.B)
      // dut.clock.step(1)
      // println(s"Cycle 2 completed, instr: ${dut.io.instr.peek()}")

      // dut.io.instr.poke("x026f3457".U)
      // dut.io.rs1_data.poke(0.S)
      // dut.io.hazard_rs1_data_in.poke(0.U)
      // // dut.io.vl_rs1_out.expect(0.U)    
      // dut.io.dmemReq.ready.poke(true.B)
      // dut.io.dmemRsp.valid.poke(true.B)
      // dut.clock.step(1)
      // println(s"Cycle 3 completed, instr: ${dut.io.instr.peek()}")

      // dut.io.instr.poke("x02440557".U)
      // dut.io.rs1_data.poke(0.S)
      // dut.io.hazard_rs1_data_in.poke(0.U)
      // // dut.io.vl_rs1_out.expect(0.U)    
      // dut.io.dmemReq.ready.poke(true.B)
      // dut.io.dmemRsp.valid.poke(true.B)
      // dut.clock.step(1)
      // println(s"Cycle 4 completed, instr: ${dut.io.instr.peek()}")
      
      // dut.io.instr.poke("x4aa11657".U)
      // dut.io.rs1_data.poke(0.S)
      // dut.io.hazard_rs1_data_in.poke(0.U)
      // // dut.io.vl_rs1_out.expect(5.U)    
      // dut.io.dmemReq.ready.poke(true.B)
      // dut.io.dmemRsp.valid.poke(true.B)
      // dut.clock.step(1)
      // println(s"Cycle 5 completed, instr: ${dut.io.instr.peek()}")

      // dut.io.instr.poke("x4aa19757".U)
      // dut.io.rs1_data.poke(0.S)
      // dut.io.hazard_rs1_data_in.poke(0.U)
      // // dut.io.vl_rs1_out.expect(5.U)    
      // dut.io.dmemReq.ready.poke(true.B)
      // dut.io.dmemRsp.valid.poke(true.B)
      // dut.clock.step(1)
      // println(s"Cycle 6 completed, instr: ${dut.io.instr.peek()}")

      // dut.io.instr.poke("x4a411857".U)
      // dut.io.rs1_data.poke(0.S)
      // dut.io.hazard_rs1_data_in.poke(0.U)
      // // dut.io.vl_rs1_out.expect(5.U)    
      // dut.io.dmemReq.ready.poke(true.B)
      // dut.io.dmemRsp.valid.poke(true.B)
      // dut.clock.step(1)
      // println(s"Cycle 7 completed, instr: ${dut.io.instr.peek()}")





      // // divv
      // dut.io.instr.poke("x82e81957".U)
      // dut.io.rs1_data.poke(0.S)
      // dut.io.hazard_rs1_data_in.poke(0.U)
      // // dut.io.vl_rs1_out.expect(5.U)    
      // dut.io.dmemReq.ready.poke(true.B)
      // dut.io.dmemRsp.valid.poke(true.B)
      // dut.clock.step(32)
      // println(s"Cycle 11 completed, instr: ${dut.io.instr.peek()}")

      // dut.io.instr.poke("x83255a57".U)
      // dut.io.rs1_data.poke(0x40400000.S)
      // dut.io.hazard_rs1_data_in.poke(0x40400000.U)
      // // dut.io.vl_rs1_out.expect(5.U)    
      // dut.io.dmemReq.ready.poke(true.B)
      // dut.io.dmemRsp.valid.poke(true.B)
      // dut.clock.step(32)
      // println(s"Cycle 12 completed, instr: ${dut.io.instr.peek()}")

      // dut.io.instr.poke("x87455b57".U)
      // dut.io.rs1_data.poke(0x40400000.S)
      // dut.io.hazard_rs1_data_in.poke(0x40400000.U)
      // // dut.io.vl_rs1_out.expect(5.U)    
      // dut.io.dmemReq.ready.poke(true.B)
      // dut.io.dmemRsp.valid.poke(true.B)
      // dut.clock.step(1)
      // println(s"Cycle 13 completed, instr: ${dut.io.instr.peek()}")


      dut.clock.step(10)
      println(s"Cycle 13 completed, instr: ${dut.io.instr.peek()}")
    }
  }
}